"""Write the OpenAPI (Swagger) spec to openapi/*.yaml.

    python -m scripts.export_openapi

Produces the complete spec plus one file per API group. FastAPI generates the spec from the routes and Pydantic
models, so these files are build output: re-run this after changing an endpoint or a schema.
`tests/test_openapi_export.py` fails when they are out of date.
"""

import os
from pathlib import Path

# Importing the app must not create data/app.db or need API keys
os.environ.setdefault("DATABASE_URL", "sqlite:///:memory:")

import yaml  # noqa: E402

from app.main import app  # noqa: E402

OUTPUT_DIR = Path(__file__).resolve().parent.parent / "openapi"
FULL_SPEC = "openapi.yaml"
GROUPS = {"tickers.yaml": "tickers", "chat.yaml": "chat"}
HEADER = "# Generated by `python -m scripts.export_openapi`. Do not edit by hand.\n"
REF_PREFIX = "#/components/schemas/"


def _referenced_schemas(node, found: set[str]) -> None:
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str) and ref.startswith(REF_PREFIX):
            found.add(ref.removeprefix(REF_PREFIX))
        for value in node.values():
            _referenced_schemas(value, found)
    elif isinstance(node, list):
        for item in node:
            _referenced_schemas(item, found)


def spec_for_tag(spec: dict, tag: str) -> dict:
    """The spec limited to one tag's operations, keeping only the schemas those operations use."""
    paths = {}
    for path, operations in spec["paths"].items():
        kept = {method: op for method, op in operations.items() if tag in op.get("tags", [])}
        if kept:
            paths[path] = kept

    all_schemas = spec.get("components", {}).get("schemas", {})
    needed: set[str] = set()
    _referenced_schemas(paths, needed)
    pending = list(needed)
    while pending:  # schemas reference other schemas
        nested: set[str] = set()
        _referenced_schemas(all_schemas[pending.pop()], nested)
        pending.extend(nested - needed)
        needed |= nested

    return {
        "openapi": spec["openapi"],
        "info": {**spec["info"], "title": f"{spec['info']['title']}: {tag}"},
        "tags": [t for t in spec.get("tags", []) if t["name"] == tag],
        "paths": paths,
        "components": {"schemas": {name: all_schemas[name] for name in sorted(needed)}},
    }


def render(spec: dict) -> str:
    return HEADER + yaml.safe_dump(spec, sort_keys=False, allow_unicode=True, width=120)


def build_files() -> dict[str, str]:
    spec = app.openapi()
    files = {FULL_SPEC: render(spec)}
    for filename, tag in GROUPS.items():
        files[filename] = render(spec_for_tag(spec, tag))
    return files


def main() -> None:
    OUTPUT_DIR.mkdir(exist_ok=True)
    for filename, content in build_files().items():
        (OUTPUT_DIR / filename).write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote openapi/{filename}")


if __name__ == "__main__":
    main()
